Makefile, env_sample.sh, src/code/Dockerfile, src/gitleaks/Dockerfile
=> rm: GOPRIVATE

src/gitleaks/go.mod, src/gitleaks/go.sum, src/gitleaks/main.go
=> add: finalizer

src/gitleaks/handler.go, src/gitleaks/main.go
=> fix: core grpc

src/code/service.go
スキャンすべき対象へのスキャン要求がなされていない可能性がある場合に、エラーを返すよう修正
=> return error when processing invoke scan

src/gitleaks/github.go
close https://github.com/ca-risken/internal-community/issues/217
Enterprise版のGitHubリポジトリの場合には、Enterprise外のユーザ（アウトサイドコラボレータ）がInternalリポジトリを参照できない問題があったため、リポジトリの取得方法を変更します。
GitHub側から、その場合にはtype=internalでの取得はできないため、type=allで取得したあとに各リポジトリのvisibilityを参照するようなロジックに変更すればできるという旨のコメントをもらえたのでその方針で行きたいと思います。
=> fix: lits org repo

src/code/client.go, src/code/main.go, src/code/service.go
=> fix: core addr

src/gitleaks/handler.go
updatedAtを取得する方法を変更しました。
今まではリポジトリ名を含んだリソースのリストを取得し、先頭のリソースのupdatedAtを見ていました。
これにより意図しないリソースのupdatedAtを取得している可能性がありました。
=> Returns a resource whose name matches the repository name

src/gitleaks/gitleaks.go, src/gitleaks/gitleaks_test.go
timeformatを変更し、意図した時間範囲のコミットをスキャンできるように修正しました。
=> Fix scanDuration

src/gitleaks/handler.go
検出されたSecretがREDACTになっている場合、該当する箇所を見つけにくいため参照できるURLを追加しました。
=> Add url for finding secret

src/gitleaks/gitleaks.go, src/gitleaks/handler.go, src/gitleaks/main.go
gitleaksの設定ファイルを外から設定できるように変更します
=> Add option for gitleaks config file

src/gitleaks/go.mod, src/gitleaks/go.sum
Update go-git to patch below PR.
https://github.com/go-git/go-git/pull/524
=> Resolve reference delta not found error

codebuild/dependency-base-image/buildspec-batch.yml, codebuild/dependency-base-image/buildspec-image.yml, codebuild/dependency-base-image/buildspec-manifest.yml, dockers/dependency-base/Dockerfile
dependencyデータソースで使用するベースイメージを作成するためのcodebuild,Dockerfileを用意します
イメージのビルド自体はcodebuildから手動で叩くことを想定しています
=> add dependency base

src/dependency/handler.go, src/dependency/main.go, src/dependency/sqs.go
src/dependency配下のエラーハンドリング改善しました。
* client生成時のエラーは呼び出し元でハンドリングするために呼び出し元に返すようにしています。
=> Improve error handling dependency

src/dependency/github.go, src/dependency/go.mod, src/dependency/go.sum, src/dependency/handler.go, src/gitleaks/github.go, src/gitleaks/go.mod, src/gitleaks/go.sum, src/gitleaks/handler.go
gitleaksのenterprise関連の箇所を削除します
=> deprecated: github enterprise

go.mod, go.sum, pkg/dependency/handler.go
=> fix: clear score

pkg/dependency/finding.go, pkg/dependency/finding_test.go, pkg/dependency/handler.go
gitleaksと同様にdependencyでもスキャンを行ったリポジトリ情報をリソースとして登録します。
=> add put resource

cmd/dependency/main.go, cmd/gitleaks/main.go, pkg/dependency/config.go
=> fix: dataousource api

cmd/dependency/main.go, cmd/gitleaks/main.go
スキャンエラーを新方式に切り替えるため、Finalyzerを削除します
=> rm: finalyzer

go.mod, go.sum, pkg/dependency/dependency.go, pkg/dependency/dependency_test.go, pkg/dependency/handler.go
たまにスキャンエラーが発生する事象を確認したのでリトライの仕組みを導入します
=> add: retry

pkg/gitleaks/handler.go
nil deriferenceエラーが発生するケースがあったので修正します
=> fix: nil deriference

pkg/dependency/dependency.go, pkg/dependency/dependency_test.go
=> enabled: retry scan

go.mod, go.sum, pkg/codescan/finding.go, pkg/codescan/finding_test.go, pkg/codescan/handler.go, pkg/codescan/recommend.go, pkg/codescan/recommend_test.go, pkg/codescan/semgrep.go, pkg/codescan/semgrep_test.go, pkg/gitleaks/finding.go, pkg/gitleaks/finding_test.go, pkg/gitleaks/handler.go, pkg/gitleaks/handler_test.go
GitleaksとCodeScanのリファクタ＋αです。
- 不要なコードの削除
- テストの追加
- 外部から参照したい関数をExpose（RISKENへPutするFindingデータ関連の処理を共通化したい）
=> Refactor: fix & expose functions

pkg/codescan/semgrep.go, pkg/codescan/semgrep_test.go
masterブランチ名を`master`決め打ちになっていたので修正します
=> fix: GitHub URL

pkg/gitleaks/finding.go, pkg/gitleaks/gitleaks.go, pkg/gitleaks/handler.go
nil dereferenceが発生していたので修正します。
=> Fix nil dereference

.github/workflows/code-butler.yml
code-butlerをcodeに導入します。
以下のコピペです。
https://github.com/marketplace/actions/code-butler-for-pr-review
=> add yaml for code-butler

pkg/gitleaks/finding.go, pkg/gitleaks/finding_test.go, pkg/gitleaks/handler.go
gitleaksのスコアを調整します。
publicの場合にはスコアを上げます。
=> fix: gitleaks score

pkg/codescan/semgrep.go, pkg/codescan/semgrep_test.go
=> fix: codescan score

codebuild/multi-arch/buildspec-batch.yml
=> upgrade: build image

pkg/dependency/finding.go, pkg/dependency/finding_test.go
- 1Finding=1脆弱性になるので、データ構造を修正
- 自動トリアージ対象のFindingはスコアを通常よりも上げます
※この対応によりデフォルトのアラートしきい値を超える可能性もある
=> Triageable Score
